import { Header } from 'semantic-ui-react'
import Head from 'next/head'
import Popular from '../components/Popular'

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Learn In Web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* 기본 컨텐츠 */}
      <div className='ui container relative left-10'>
        <h3 className="text-3xl font-bold">인기 문제</h3>
        <Popular />
      </div>
    </div>
  )
}