import {Header} from 'semantic-ui-react'
import Head from 'next/head'

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Learn In Web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* 기본 컨텐츠 */}
      <Header as='h3' textAlign='center'>인기 문제</Header>
      
    </div>
  )
}